--- !ditz.rubyforge.org,2008-03-06/project 
name: pitz
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: pitz
- !ditz.rubyforge.org,2008-03-06/component 
  name: model
- !ditz.rubyforge.org,2008-03-06/component 
  name: controller
- !ditz.rubyforge.org,2008-03-06/component 
  name: view
releases: []

